steps:
  # Build the Docker image for push-to-prod GitHub App
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/push-to-prod-builds/push-to-prod:$COMMIT_SHA', '.']

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/push-to-prod-builds/push-to-prod:$COMMIT_SHA']

  # Deploy to Cloud Run with environment variables and secrets
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'push-to-prod'
      - '--image'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/push-to-prod-builds/push-to-prod:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--update-env-vars'
      - 'APP_ID=1130707,PORT=8080,LOG_LEVEL=trace'
      - '--set-secrets'
      - 'WEBHOOK_SECRET=push-to-prod-webhook-secret:latest,ANTHROPIC_API_KEY=push-to-prod-anthropic-key:latest,JIRA_EMAIL=push-to-prod-jira-email:latest,JIRA_API_TOKEN=push-to-prod-jira-token:latest'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/push-to-prod-builds/push-to-prod:$COMMIT_SHA'
  
options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: 'us-central1'