services:
  github-app:
    build:
      context: ./github-app
    ports:
      - "8080:8080"
    environment:
      - PRIVATE_KEY_PATH=/usr/src/app/private-key.pem
    volumes:
      - ./github-app/pushtoprodbot-dev.2025-03-03.private-key.pem:/usr/src/app/private-key.pem
    env_file:
      - ./github-app/.env

  # You can add more services here as needed, like blast-radius, syntropy, and frontend
  # blast-radius:
  #   build:
  #     context: ./blast-radius-app
  #   ports:
  #     - "8081:8080"
  #   env_file:
  #     - ./blast-radius-app/.env

  # syntropy:
  #   build:
  #     context: ./syntropy-app
  #   ports:
  #     - "8082:8080"
  #   env_file:
  #     - ./syntropy-app/.env
  
  # frontend:
  #   build:
  #     context: ./frontend-app
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - ./frontend-app/.env 