services:
  github-app:
    build:
      context: ./server/github
    ports:
      - "8080:8080"
    environment:
      - PRIVATE_KEY_PATH=/usr/src/app/private-key.pem
      - LOG_LEVEL=trace
    volumes:
      - ./server/github/pushtoprodbot-dev.2025-03-03.private-key.pem:/usr/src/app/private-key.pem
    env_file:
      - ./server/github/.env
    networks:
      - app-network

  blast-radius:
    build:
      context: ./server/blast-radius
    ports:
      - "8081:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - ./server/blast-radius:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    # env_file:
    #  - ./server/blast-radius/.env

  syntropy:
    build:
      context: ./server/syntropy
    ports:
      - "8082:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - ./server/syntropy:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    # env_file:
    #   - ./server/syntropy/.env
  
  frontend:
    build:
      context: ./client
    ports:
      - "3000:8080"
    environment:
      - NODE_ENV=development
      - NEXTAUTH_URL=http://localhost:3000
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    env_file:
      - ./client/.env.local
    depends_on:
      - github-app

networks:
  app-network:
    driver: bridge