from pydantic import BaseModel, Field


class CalculationRequestModel(BaseModel):

    summary: str = Field(
        ...,
        description="The summary generated by the code analysis to be used for calculating the blast radius")

