from pydantic import BaseModel, Field

from typing import Optional


class CalculationRequestModel(BaseModel):

    summary: str = Field(
        ...,
        description="The summary generated by the code analysis to be used for calculating the Blast Radius"
    )

    max_items: Optional[int] = Field(
        20,
        description="The maximum number of issues in the Blast Radius to return"
    )


class CalculationResponseModel(BaseModel):

    relevant_issues: list = Field(
        ...,
        description="The list of relevant issues found by embedding-based cosine similarity search."
    )
